apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  labels:
    run: jenkins

spec:
  selector: 
    run: jenkins
  type: NodePort  
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32000